<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6db373b1-df03-4edc-ba1f-7fee7ec35142</UserSecretsId>
    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.13" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Gym.API\DTOs\Member\" />
    <Folder Include="Gym.API\DTOs\Membership\" />
    <Folder Include="Gym.API\DTOs\Facility\" />
    <Folder Include="Gym.API\DTOs\Checkin\" />
    <Folder Include="Gym.API\DTOs\Invoice\" />
    <Folder Include="Gym.API\DTOs\Payment\" />
    <Folder Include="Gym.API\DTOs\Session\" />
    <Folder Include="Gym.API\DTOs\Schedule\" />
    <Folder Include="Gym.API\DTOs\Trainer\" />
  </ItemGroup>

</Project>
